# Topics

# Notes

# Mistakes and Improvements
1. Error "object is not subscriptable" means we have used [] square brackets in place of () round brackets

In [2]:
import pandas as pd
import numpy as np

In [7]:
car_df = pd.read_csv("7.1 car-sales.csv.csv")
car_df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [8]:
# String is shown as object in python
car_df.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [12]:
# car_df.describe will return its attribute. But car_df.describe()  will show below details for integer and float
car_df.describe()

Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [13]:
rutul_df = pd.read_csv("rutul.csv", skiprows=[7])
rutul_df

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri
5       Jay     NaN        NaN

# To find count of non-null values , and other description

In [19]:
rutul_df.describe()
# Note : Because of null value in Jay's Number...it is showing output as 5 instead of 6. Thus, count shows all non-null values.

Number
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [20]:
# List is [9,12,2,7,1,35,50,38,55,70,10,19]
# First arrange list in assending order [1,2,7,9,10,12,19,35,38,50,55,70]
# min is 1
# 25th percentile record i.e. 25% = 7
# 50th percentile record i.e. 50% = 12
# 75th percentile record i.e. 75% = 38
# max is 70 

### By default the describe() operation returns description of numerical data only.
### If we want to get description of object (i.e. string) then we have to do as follows

In [25]:
# Multiple columns ne list tarike api che
car_df[['Make','Colour','Price']].describe()

Make Colour      Price
count       10     10         10
unique       4      5          9
top     Toyota  White  $7,000.00
freq         4      4          2

In [26]:
# freq ni upar top che. top ni values akha data set ma ketli var repeat thai che, ae freq ma batave. Toyota 4 vakhat che apda dataset ma, White b 4 times and $7000 2 times che.

## If we have 1000 columns and apde 1000 mathi jetla columns string data type na hoy emnu description joiye. To darek column nu name list ma individually na api sakiye to below technique use karvi.

In [27]:
car_df.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [28]:
# Left side index nu name che and jya object che tya true che
car_df.dtypes == 'object'

Make              True
Colour            True
Odometer (KM)    False
Doors            False
Price             True
dtype: bool

In [32]:
# jya data type object hoy ae index apad ne return kare
car_df.dtypes[car_df.dtypes == 'object'].index

Index(['Make', 'Colour', 'Price'], dtype='object')

In [37]:
# Upar nu akhu apde a ma store karisu and dataframe ma list ni jagiyaye apisu , and then describe() method use karisu
a = car_df.dtypes[car_df.dtypes == 'object'].index
car_df[a].describe()

Make Colour      Price
count       10     10         10
unique       4      5          9
top     Toyota  White  $7,000.00
freq         4      4          2

In [38]:
# Above is explanation. You can directly do as follows
b = car_df.dtypes[car_df.dtypes == 'object'].index
car_df[b].describe()

Make Colour      Price
count       10     10         10
unique       4      5          9
top     Toyota  White  $7,000.00
freq         4      4          2

In [39]:
c = car_df.dtypes[car_df.dtypes == 'int64'].index
car_df[c].describe()

Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

## Different column operations

In [49]:
car_df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [50]:
car_df['Make'][4]

'Nissan'

In [51]:
# Slice from 2 to 6 like we did in list during python
car_df['Make'][2:7]

2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
Name: Make, dtype: object

In [52]:
# 2 to 6 with Jump 2
car_df['Make'][2:7:2]

2    Toyota
4    Nissan
6     Honda
Name: Make, dtype: object

In [56]:
# We can pass list instead of 'Make'
l = ['Make','Colour']
car_df[l][2:7:2]
# or  car_df[ ['Make','Colour'] ] [2:7:2]


Make Colour
2  Toyota   Blue
4  Nissan  White
6   Honda   Blue

In [62]:
# Store described result in dataframe
x = car_df[l][2:7:2]
x

Make Colour
2  Toyota   Blue
4  Nissan  White
6   Honda   Blue

### To sort a column

In [58]:
sorted(car_df['Make'][2:7:2])

['Honda', 'Nissan', 'Toyota']

### To find categories or unique values in a column

In [63]:
car_df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [64]:
car_df['Doors']

0    4
1    4
2    3
3    5
4    4
5    4
6    4
7    4
8    4
9    4
Name: Doors, dtype: int64

In [74]:
cat = pd.Categorical(car_df['Doors'])
cat
# We get whole column data and there are theree unique values or categories in Doors column 3,4,5

[4, 4, 3, 5, 4, 4, 4, 4, 4, 4]
Categories (3, int64): [3, 4, 5]

In [75]:
type(cat)

pandas.core.arrays.categorical.Categorical

In [76]:
# To convert cat into list
l = list(cat)

In [77]:
type(l)

list

## Lets perform mapping for 'Doors' i.e. convet 3 to Three , 4 to Four, 5 to Five

In [85]:
map_df = list(car_df['Doors'])
map_df

[4, 4, 3, 5, 4, 4, 4, 4, 4, 4]

In [86]:
new_col = []
for i in map_df:
    if (i == 3):
        new_col.append('Three')
    if (i == 4):
        new_col.append('Four')
    if (i == 5):
        new_col.append('Five')
new_col

['Four',
 'Four',
 'Three',
 'Five',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four']

In [96]:
mapped_df = car_df
mapped_df['New Doors'] = new_col
mapped_df
# To make changes in existing column 
# mapped_df['Doors'] = new_col

Make Colour  Odometer (KM)  Doors       Price New Doors
0  Toyota  White         150043      4   $4,000.00      Four
1   Honda    Red          87899      4   $5,000.00      Four
2  Toyota   Blue          32549      3   $7,000.00     Three
3     BMW  Black          11179      5  $22,000.00      Five
4  Nissan  White         213095      4   $3,500.00      Four
5  Toyota  Green          99213      4   $4,500.00      Four
6   Honda   Blue          45698      4   $7,500.00      Four
7   Honda   Blue          54738      4   $7,000.00      Four
8  Toyota  White          60000      4   $6,250.00      Four
9  Nissan  White          31600      4   $9,700.00      Four

### Sudhanshu ae juni column no first letter lidho and navi column ma first letters ave evi column banai 

## Extract all indexes which is having null values in a particular column

In [97]:
rutul_df

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri
5       Jay     NaN        NaN

In [105]:
# don't make mistake in syntax or spelling
# Got output as 5 bcoz at index 5 we have null
import numpy as np
missing = np.where(rutul_df['Number'].isnull() == True)
missing

(array([5], dtype=int64),)

In [106]:
l = list(missing)

In [107]:
type(l)

list

In [108]:
missing2 = pd.read_csv("checknull.csv")
missing2

Name  Number
0    a     1.0
1    b     NaN
2    c     NaN
3    d     2.0
4    e     NaN
5    f     5.0
6    g     8.0

In [112]:
# Check for null
missing2['Number'].isnull()

0    False
1     True
2     True
3    False
4     True
5    False
6    False
Name: Number, dtype: bool

In [114]:
np.where(missing2['Number'].isnull() == True)

(array([1, 2, 4], dtype=int64),)

In [113]:
# Give array where 'Number' is null
missing3 = np.where(missing2['Number'].isnull() == True)
missing3

(array([1, 2, 4], dtype=int64),)

In [115]:
rutul_df

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri
5       Jay     NaN        NaN

In [119]:
max(rutul_df['Number'])

5.0

In [120]:
# To return index
rutul_df['Number'] == max(rutul_df['Number'])

0    False
1    False
2    False
3    False
4     True
5    False
Name: Number, dtype: bool

## To get indexes of rows from a partiular condition
### Pronounce as "Give array where condition"

In [122]:
import numpy as np
np.where(rutul_df['Number'] == max(rutul_df['Number']))

(array([4], dtype=int64),)

## Now we will learn to access rows with .loc , .iloc , .ix
iloc stands for integer location i.e. default row index in form of integer
loc etle je name apde apyu hoy ae or apde name na apyu hooy to default lai le

In [126]:
rutul_df

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri
5       Jay     NaN        NaN

In [123]:
row_index = np.where(rutul_df['Number'] == max(rutul_df['Number']))
rutul_df.iloc[row_index]

Name  Number       Food
4  Vaishvik     5.0  Pani-puri

In [125]:
# To get particular columns (Note : to access multiple columns, we pass list)
rutul_df.iloc[row_index][ ['Number','Food'] ]

Number       Food
4     5.0  Pani-puri

In [128]:
# Get person name who had Vadapav
Vadapav_index = np.where(rutul_df['Food'] == 'Vadapav')
# rutul_df.iloc[Vadapav_index]    to get full row
rutul_df.iloc[Vadapav_index][ ['Name'] ]

Name
1  Hrithik

## Concatination of columns

In [143]:
conc = pd.read_csv("concat.csv")
conc

name1  num1 name2  num2
0     a     3     n     5
1     v     3     m     9
2     s     2     f     6
3     q     5     j     4
4     p     2     i     7

In [144]:
# For two integer types, it will perform sum
conc['num1'] + conc['num2']

0     8
1    12
2     8
3     9
4     9
dtype: int64

In [151]:
# For two string types, it will perform concatination
conc['name1'] + conc['name2']
# conc['name1'] + " hello " + conc['name2']      this also works fine

0    an
1    vm
2    sf
3    qj
4    pi
dtype: object

In [152]:
# conc['num1'] + conc['name2']          will show error as one is integer and second is column

# Create Custom Series

In [164]:
# Note : pd.Series(data, index=labels)     in bracket data always comes first and then indes....if done vice versa then error "positional"
labels = ['a','b','c']
data = [1,5,8]
a = pd.Series(data, index=labels)     # Directly index=['a','b','c'] will also work fine
a

a    1
b    5
c    8
dtype: int64

In [167]:
# Eventhough we give our own index...we can still use default index from 0
a[0]
# a['a']     will also give same output

1

In [163]:
# Default index starts from 0
pd.Series(data)

0    1
1    5
2    8
dtype: int64

In [172]:
ser1 = pd.Series([1,'b',7,9], index=[8,7,6,3])
ser2 = pd.Series(['CA','US','IN','NE'], index=[1,2,3,4])

In [173]:
ser1

8    1
7    b
6    7
3    9
dtype: object

In [174]:
ser2

1    CA
2    US
3    IN
4    NE
dtype: object

In [175]:
ser1[0:3:2]

8    1
6    7
dtype: object

In [177]:
# In index 2nd and 4th are different
ser3 = pd.Series([1,3,4,2] , index=['CA','CB','AU','FD'])
ser4 = pd.Series([5,2,4,1] , index=['CA','CZ','AU','JK'])

In [180]:
# Jya index same hoy tya j addition and multiplication thay
ser3 + ser4

AU    8.0
CA    6.0
CB    NaN
CZ    NaN
FD    NaN
JK    NaN
dtype: float64

In [181]:
ser3 * ser4

AU    16.0
CA     5.0
CB     NaN
CZ     NaN
FD     NaN
JK     NaN
dtype: float64

### Convert dictionary into dataframe
index ma jetli value apiye, etli var ae lambay

In [168]:
d = { 'a':"hello" , 'b':123 , 'c':'t56'}
d

{'a': 'hello', 'b': 123, 'c': 't56'}

In [170]:
# temp_df = pd.DataFrame(d)    will give error...we must give index
temp_df = pd.DataFrame(d, index=['s','r','l','h'])
temp_df

a    b    c
s  hello  123  t56
r  hello  123  t56
l  hello  123  t56
h  hello  123  t56