# Topics

# Notes
1. .iloc[]  etle default index o,1,2,3,......
2. By default .drop() will look into row for deletion as axis=0 by default. So, axis=0 for row and axis=1 for column
3. .drop() can be used to drop both rows and columns so we have to specify within the bracket (what we want to delete)
4. .drop() in index takes actual names that we gave...not default index
5. Outer DFName [ ] is must when working with condition otherwise it will return True False 

# Mistakes and Improvements

In [1]:
import pandas as pd
import numpy as np

### Convert array into DataFrame

In [2]:
from numpy.random import randn as rn
# To generate same random data...if np.random.seed(101) is commented then it will always generate new random data every time we execute this cell
np.random.seed(101)
mat = rn(4,4)
mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651]])

In [3]:
row_label = ['A','B','C','D']
col_label = ['W','X','Y','Z']
# The format must be this way ( data ,index= [] , columns= [] )
mat_df = pd.DataFrame(mat, row_label, col_label)
mat_df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [4]:
my_data = np.array([ [2,6,4,3],
                     [3,87,43,2],
                    [7,4,5,6],
                    [23,56,78,90] ])
my_data

array([[ 2,  6,  4,  3],
       [ 3, 87, 43,  2],
       [ 7,  4,  5,  6],
       [23, 56, 78, 90]])

In [5]:
# my_dataframe = pd.DataFrame(my_data, index= ['q','w','e','r'], columns=[1,'a','B','S2'])    This also work
my_dataframe = pd.DataFrame(my_data, ['q','w','e','r'], [1,'a','B','S2'])
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [6]:
# Default row and column
my_dataframe2 = pd.DataFrame(my_data)
my_dataframe2

0   1   2   3
0   2   6   4   3
1   3  87  43   2
2   7   4   5   6
3  23  56  78  90

In [7]:
# We only want to give columns as required and row as default from 0,1,2,3.....
# This won't work      my_dataframe3 = pd.DataFrame(my_data,,col_label)
my_dataframe3 = pd.DataFrame(my_data, columns=col_label)
my_dataframe3

W   X   Y   Z
0   2   6   4   3
1   3  87  43   2
2   7   4   5   6
3  23  56  78  90

In [8]:
my_dataframe3.loc[[1,3]]

W   X   Y   Z
1   3  87  43   2
3  23  56  78  90

In [9]:
my_dataframe3.loc[[1,3]]

W   X   Y   Z
1   3  87  43   2
3  23  56  78  90

In [10]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [11]:
my_dataframe.iloc[ [1,3] ]

1   a   B  S2
w   3  87  43   2
r  23  56  78  90

In [12]:
my_dataframe.loc[ ['w','r'] ]

1   a   B  S2
w   3  87  43   2
r  23  56  78  90

### To get columns in our required sequence

In [13]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [14]:
my_dataframe[ [1,'S2','a'] ]

1  S2   a
q   2   3   6
w   3   2  87
e   7   6   4
r  23  90  56

In [15]:
# w and e row mathi 1 and 'B' column no data
my_dataframe[ [1,'B'] ].iloc[ [1,2] ]
# my_dataframe[ [1,'B'] ].loc[ ['w','e'] ]

1   B
w  3  43
e  7   5

In [16]:
# Give index as required
my_dataframe[ [1,'B'] ].iloc[ [2,1] ]

1   B
e  7   5
w  3  43

## To access index and columns both using .iloc[ [row list], [column list] ] 

In [17]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [18]:
my_dataframe.iloc[ [2,1,3] , [3,1] ]

S2   a
e   6   4
w   2  87
r  90  56

In [19]:
# This both work 
# my_dataframe.iloc[ [0,3] , [0,3] ]
my_dataframe.iloc[ [0,-1] , [0,-1] ]

1  S2
q   2   3
r  23  90

In [20]:
# Printed two dataframes....and \n works here.....printed - like sudhanshu, which looks good to show some seperation
# , ma by default 1 space lai le, and concate i.e. + ma space na le 
# Try using print(my_dataframe + "\n" + "-"*30) will give error as int + str
print(my_dataframe , "\n" + "-"*30)
print(my_dataframe3)

    1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90 
------------------------------
    W   X   Y   Z
0   2   6   4   3
1   3  87  43   2
2   7   4   5   6
3  23  56  78  90


In [21]:
# By writing this only last executed
my_dataframe
my_dataframe3

W   X   Y   Z
0   2   6   4   3
1   3  87  43   2
2   7   4   5   6
3  23  56  78  90

## Using .drop() for deleting rows and columns

In [22]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [23]:
# .drop can be used to delete both rows and columns, so we have to specify
my_dataframe.drop(index=['q','e'], columns=[1,'B'])

a  S2
w  87   2
r  56  90

In [24]:
my_x =  my_dataframe.drop(index=['q','e'], columns=[1,'B'])
my_x

a  S2
w  87   2
r  56  90

In [25]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

### Understanding axis  for .drop() 

In [26]:
# By default it takes row for deletion as default axis=0. So, if we directly give column it will give error
my_dataframe.drop(['w','r'])

1  a  B  S2
q  2  6  4   3
e  7  4  5   6

In [27]:
my_dataframe.drop([1,'S2'], axis=1)

a   B
q   6   4
w  87  43
e   4   5
r  56  78

In [28]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [29]:
rows = list(range(0,3))
cols = list(range(1,4))
my_dataframe.iloc[ rows , cols ]

a   B  S2
q   6   4   3
w  87  43   2
e   4   5   6

In [30]:
# This don't work as drop requires actual names that we gave...not default index from 0,1,2,3,....
my_dataframe.drop( index=rows , columns=cols )

KeyError: '[0 1 2] not found in axis'

## Checking Dataframe values with conditional operator

In [31]:
my_dataframe

1   a   B  S2
q   2   6   4   3
w   3  87  43   2
e   7   4   5   6
r  23  56  78  90

In [32]:
# Check for all values of dataframe "condition"
# We can also add some specific condition with .iloc or .loc
# All three works well n good
# my_dataframe.iloc[ [0,1],[0,1] ]  > 50
# my_dataframe.loc[ ['q','w'] , [1,'a']]  > 50
my_dataframe > 50

1      a      B     S2
q  False  False  False  False
w  False   True  False  False
e  False  False  False  False
r  False   True   True   True

## Creating Matrix , then creating DataFrame

In [33]:
matrix_data = np.matrix( '26,34,57;32,77,85;23,11,53;56,34,29')
matrix_data

matrix([[26, 34, 57],
        [32, 77, 85],
        [23, 11, 53],
        [56, 34, 29]])

In [34]:
type(matrix_data)

numpy.matrix

In [35]:
new_array = np.array([ [2,3,53],
                       [39,64,31],
                       [43,90,88],
                       [66,73,25] ])
new_array

array([[ 2,  3, 53],
       [39, 64, 31],
       [43, 90, 88],
       [66, 73, 25]])

In [36]:
type(new_array)

numpy.ndarray

In [37]:
ab = pd.DataFrame(matrix_data , index=['A','B','C','D'] , columns=['W',3,'S#'])
ab

W   3  S#
A  26  34  57
B  32  77  85
C  23  11  53
D  56  34  29

In [38]:
cd = pd.DataFrame(new_array , index=['A','B','C','D'] , columns=['W',3,'S#'])
cd

W   3  S#
A   2   3  53
B  39  64  31
C  43  90  88
D  66  73  25

### Return True or False from condition

In [39]:
# return true false  
cd['W'] > 40

A    False
B    False
C     True
D     True
Name: W, dtype: bool

## Return actual values from condition...just add extra DFNAME [ ] on outer side

In [40]:
# return in form of dataframe, so add cd [ ]
cd [ cd['W'] > 40 ]

W   3  S#
C  43  90  88
D  66  73  25

In [41]:
# This did not work         cd [ cd['W'] > 40 and cd[3] > 80 ]

In [42]:
# This also did not work    cd [ (cd['W'] > 40) and (cd[3] > 80) ]
cd [ (cd['W'] > 40) & (cd[3] > 80) ]

W   3  S#
C  43  90  88

In [43]:
new_data = np.array([ [22,66,140],
                      [42,70,148],
                      [30,62,125],
                      [35,68,160],
                      [25,62,152]])
rows = ['A','B','C','D','E']
cols = ['Age','Height','Weight']

In [44]:
health_data = pd.DataFrame(new_data, index = rows , columns = cols)
health_data

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [45]:
health_data [ (health_data['Age']>30) & (health_data['Height']>65) & (health_data['Weight']>125)]

Age  Height  Weight
B   42      70     148
D   35      68     160

## Reset Index and keep old index with .reset_index() method

In [46]:
health_data

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [47]:
reset_in = health_data.reset_index()
reset_in

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [48]:
# We can do this to avoid extra index column
reset_in.drop( columns=['index'] )

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [49]:
# This one is better
# We can also do this to avoid extra index column
reset_in2 = health_data.reset_index(drop=True)
reset_in2

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

## Understanding split() function

In [50]:
# By default parameter is space
"Doctor Engineer Lawyer Teacher Police".split()

['Doctor', 'Engineer', 'Lawyer', 'Teacher', 'Police']

In [51]:
"Doctor,kEngineer,kLawyer,kTeacher,kPolice".split(",k")

['Doctor', 'Engineer', 'Lawyer', 'Teacher', 'Police']

In [52]:
health_data

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [53]:
health_data['New'] = "Doctor Engineer Lawyer Teacher Police".split()
health_data

Age  Height  Weight       New
A   22      66     140    Doctor
B   42      70     148  Engineer
C   30      62     125    Lawyer
D   35      68     160   Teacher
E   25      62     152    Police

## Using  set_index   OR Use any column as index 

In [54]:
health_data.set_index('New')

Age  Height  Weight
New                          
Doctor     22      66     140
Engineer   42      70     148
Lawyer     30      62     125
Teacher    35      68     160
Police     25      62     152

# Multi-index  OR hierarchy 

In [55]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

In [56]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [57]:
hier = list(zip(outside,inside))
hier

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

#### From tuples we are creating Multi-index

In [58]:
# This step is must to implement multi index concept...and also note the above cell also
hier_index = pd.MultiIndex.from_tuples(hier)
print(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [59]:
type(hier_index)

pandas.core.indexes.multi.MultiIndex

In [60]:
# np.round -0.54 jevi value ne nearest integer value jode round off kari de. like -0.56 becomes -2
# With random data
df1 = pd.DataFrame( data=np.round(rn(6,3)) ,index=hier_index , columns=['A','B','C'])
print(df1)

        A    B    C
G1 1  0.0  2.0  3.0
   2  1.0  0.0  2.0
   3 -2.0 -1.0 -0.0
G2 1  0.0  0.0  0.0
   2  1.0  0.0  1.0
   3  0.0 -0.0 -1.0


In [61]:
# With array
td = np.array([ [4,7,3],
                [54,2,67],
                [33,74,43],
                [3,6,5],
                [4,9,8],
                [0,7,3]])

In [62]:
df2 = pd.DataFrame( data=td ,index=hier_index , columns=['A','B','C'])
print(df2)

       A   B   C
G1 1   4   7   3
   2  54   2  67
   3  33  74  43
G2 1   3   6   5
   2   4   9   8
   3   0   7   3


In [63]:
df2.loc['G1'].loc[3,['B','C']]

B    74
C    43
Name: 3, dtype: int32

In [64]:
df2.loc['G1'].loc[ [2,3] ,['B','C']]

B   C
2   2  67
3  74  43

In [65]:
# This below shows error. I think for first hierarchy 'G1' ...we have to access it with loc
# Notice difference between this cell and below cell
df2.iloc[0].loc[ [2,3] ,['B','C']]

IndexingError: Too many indexers

In [66]:
df2.loc['G1'].iloc[ [1,2] ,[1,2]]

B   C
2   2  67
3  74  43

## Task by sir...3 level

In [67]:
l1 = ['A','A','A','B','B','B','C','C','C']
l2 = [1,2,3,1,2,3,1,2,3]
l3 = [1,2,3,4,5,6,7,8,9]

In [68]:
l = list(zip(l1,l2,l3))

In [69]:
hier_index3 = pd.MultiIndex.from_tuples(l)
type(hier_index3)

pandas.core.indexes.multi.MultiIndex

In [70]:
df3 = pd.DataFrame( data=np.round(rn(9,3)) ,index=hier_index3 , columns=['A','B','C'])
print(df3)

         A    B    C
A 1 1 -1.0  0.0 -0.0
  2 2  2.0  0.0  2.0
  3 3 -1.0  0.0 -1.0
B 1 4  0.0  1.0 -0.0
  2 5 -0.0  1.0  2.0
  3 6 -1.0 -1.0 -0.0
C 1 7  0.0 -0.0  1.0
  2 8  1.0 -1.0  2.0
  3 9 -1.0  1.0  0.0


## Drop all rows with NaN values with .dropna()

In [71]:
rutul_df = pd.read_csv(r'C:\Users\Samu\Desktop\INEURON assignments and jupynotes\PANDAS practice\rutul.csv' ,skiprows=[7])
rutul_df

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri
5       Jay     NaN        NaN

In [72]:
rutul_df.dropna()

Name  Number       Food
0     Rutul     1.0   Sandwich
1   Hrithik     2.0    Vadapav
2      Yash     3.0     Faluda
3     Karan     4.0      Toast
4  Vaishvik     5.0  Pani-puri

In [73]:
# For null in array or anywhere we have to do np.nan
null_data = np.array([ [1,np.nan,5,6],
                       [2,np.nan,np.nan,7],
                       [2,np.nan,np.nan,np.nan],
                       [2,5,6,9]])

In [74]:
null_data

array([[ 1., nan,  5.,  6.],
       [ 2., nan, nan,  7.],
       [ 2., nan, nan, nan],
       [ 2.,  5.,  6.,  9.]])

In [75]:
null_df = pd.DataFrame(null_data , columns=['A','B','C','D'])
null_df

A    B    C    D
0  1.0  NaN  5.0  6.0
1  2.0  NaN  NaN  7.0
2  2.0  NaN  NaN  NaN
3  2.0  5.0  6.0  9.0

### Set Threshold to null values

In [76]:
# By default axis is 0 here....that is it will drop all rows with nan
null_df.dropna()

A    B    C    D
3  2.0  5.0  6.0  9.0

In [77]:
# axis =1 for column
null_df.dropna(axis=1)

A
0  1.0
1  2.0
2  2.0
3  2.0

In [78]:
# atli NON-nan values joiye >=2
null_df.dropna(thresh=2)

A    B    C    D
0  1.0  NaN  5.0  6.0
1  2.0  NaN  NaN  7.0
3  2.0  5.0  6.0  9.0

In [79]:
null_df.dropna(thresh=1)

A    B    C    D
0  1.0  NaN  5.0  6.0
1  2.0  NaN  NaN  7.0
2  2.0  NaN  NaN  NaN
3  2.0  5.0  6.0  9.0

In [80]:
null_df.dropna(thresh=3)

A    B    C    D
0  1.0  NaN  5.0  6.0
3  2.0  5.0  6.0  9.0